post http://localhost:3001/api/writers/
Content-Type: application/json

{
    "firstName": "Harvey",
    "lastName": "Specter",
    "writerGenres": ["Business", "Cars"],
    "writerDescription": "Car fan, hedge fund investor",
	"oneArticlePrice": 1,
	"montlySubscriptionPrice": 10,
	"yearlySubscriptionPrice": 100
}