post http://localhost:3001/api/writers/
Content-Type: application/json

{
    "firstName": "Dummy",
    "lastName": "Dummy",
    "userName": "DummyD",
    "writerGenres": ["Business", "Cars"],
    "writerDescription": "lorem ipsum, lorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsum",
	"oneArticlePrice": 1,
	"montlySubscriptionPrice": 10,
	"yearlySubscriptionPrice": 100,
	"password": "dummydummy"
}