require('dotenv').config()

let PORT = process.env.PORT
let MONGODB_URI = process.env.MONGODB_URI

let READER_ACCESS_TOKEN_SECRET = process.env.READER_ACCESS_TOKEN_SECRET
let READER_ACCESS_TOKEN_LIFE = process.env.READER_ACCESS_TOKEN_LIFE

let READER_REFRESH_TOKEN_SECRET = process.env.READER_REFRESH_TOKEN_SECRET
let READER_REFRESH_TOKEN_LIFE = process.env.READER_REFRESH_TOKEN_LIFE


let WRITER_ACCESS_TOKEN_SECRET = process.env.WRITER_ACCESS_TOKEN_SECRET
let WRITER_ACCESS_TOKEN_LIFE = process.env.WRITER_ACCESS_TOKEN_LIFE

let WRITER_REFRESH_TOKEN_SECRET = process.env.WRITER_REFRESH_TOKEN_SECRET
let WRITER_REFRESH_TOKEN_LIFE = process.env.WRITER_REFRESH_TOKEN_LIFE

// For testing
if (process.env.NODE_ENV === 'test') {
	MONGODB_URI = process.env.TEST_MONGODB_URI
}

module.exports = {
	PORT,
	MONGODB_URI,
	READER_ACCESS_TOKEN_SECRET,
	READER_ACCESS_TOKEN_LIFE,
	READER_REFRESH_TOKEN_SECRET,
	READER_REFRESH_TOKEN_LIFE,
	WRITER_ACCESS_TOKEN_SECRET,
	WRITER_ACCESS_TOKEN_LIFE,
	WRITER_REFRESH_TOKEN_SECRET,
	WRITER_REFRESH_TOKEN_LIFE
}