require('dotenv').config()

let PORT = process.env.PORT
let MONGODB_URI = process.env.MONGODB_URI
let ACCESS_TOKEN_SECRET = process.env.ACCESS_TOKEN_SECRET
let ACCESS_TOKEN_LIFE = process.env.ACCESS_TOKEN_LIFE
let REFRESH_TOKEN_SECRET = process.env.REFRESH_TOKEN_SECRET
let REFRESH_TOKEN_LIFE = process.env.REFRESH_TOKEN_LIFE

module.exports = {
	PORT,
	MONGODB_URI,
	ACCESS_TOKEN_SECRET,
	ACCESS_TOKEN_LIFE,
	REFRESH_TOKEN_SECRET,
	REFRESH_TOKEN_LIFE
}